### ISSUE TITLE
Docs: Example lists "token" instead of "refreshToken"

### ISSUE THREAD

**Issue by quabey** [medrunner-services/api-client-ts#33]
In the [Docs - Getting Started](https://medrunner.dev/guides/getting-started.html), [Docs - Auth](https://medrunner.dev/guides/authentication.html), and in the README, the token is used as an example on how to create a basic request. However, its not mentioning that the token first has to be exchanged using the refreshToken. 

Using the refreshToken in the examples would be more straightforward, when provided a basic code snipped for getting started.

**Comment by charliefoxtwo** [comment]
`token` as a config parameter was a relic of the past (and as can be seen in the readme, it used to be a function as well).

`refreshToken` should be used for API tokens. `accessToken` can be used for tokens received via `/auth/exchange`. The docs are definitely outdated. Thanks for reporting!
